youtube_channel_urls:
  - https://www.youtube.com/@coreyms
  - https://www.youtube.com/@ShawhinTalebi
  - https://www.youtube.com/@AndrejKarpathy
  - https://www.youtube.com/@engineerprompt
  - https://www.youtube.com/@CodeEmporium
  - https://www.youtube.com/@SerranoAcademy
  - https://www.youtube.com/@underfitted
  - https://www.youtube.com/@venelin_valkov
  - https://www.youtube.com/@Siddhardhan
  - https://www.youtube.com/@AbhishekVeeramalla
  - https://www.youtube.com/@umarjamilai
  - https://www.youtube.com/@patloeber
  - https://www.youtube.com/@3blue1brown
  - https://www.youtube.com/@mathbyteacademy
  - https://www.youtube.com/@MPrashantAcademy
  - https://www.youtube.com/@NeuralNine
  - https://www.youtube.com/@EcZachly_